name: Deploy BurgerTable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build JAR with Gradle
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t kwongeono/burgertable:latest .

      - name: Push Docker image to Docker Hub
        run: docker push kwongeono/burgertable:latest